# 오더러 기관 ID생성 설정
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - localhost

# 피어기관 ID생성 설정
PeerOrgs:
#   org1 설정
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUS: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
      
#   org2 설정
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUS: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
